### ISSUE TITLE
human36m GT SMPL parameter

### ISSUE THREAD

**Issue by sunwonlikeyou** [HongwenZhang/PyMAF#10]
You said "The ground truth SMPL parameters in Human3.6M are generated by applying MoSH [34] to the sparse 3D MoCap marker data, as done in Kanazawa et al. "
I have angle files,3D points of Human3.6M. But i dont know how to SMPL parameters from the dataset.
Do you have code ? or Is there other data from Human3.6M??

**Comment by HongwenZhang** [comment]
Hi, we used the moshed labels shared in [HMR](https://github.com/akanazawa/hmr/blob/master/doc/train.md#download-datasets). Unfortunately, the moshed labels can not be redistributed publicly due to the license issue. However, [this repo](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) may still help you get the data and labels.

**Comment by sunwonlikeyou** [comment]
Thank you for reply!
Shared link just give me 3D,2D poses, but I want to get GT SMPL parameters
of Human36M.
So.. Can I receive moshed labels of Human36M..? It's just research purpose
and I want to compare it with pseudo gt parameters.

Thank you very much.
Have a nice day.

2021년 6월 16일 (수) 오후 9:31, Hongwen Zhang ***@***.***>님이 작성:

**Comment by HongwenZhang** [comment]
Please see [this link](tinyurl.com/cstcloud).
